### ISSUE TITLE
Allow JSON imports

### ISSUE THREAD

**Issue by ColinTimBarndt** [codemirror/buildhelper#2]
Buildhelper currently does not support JSON imports for TypeScript, which requires the `@rollup/plugin-json` plugin. This feature would be nice to have at least as an option. A codemirror theme plugin I'm working on depends on JSON imports because themes are defined as JSON there.

**Comment by marijnh** [comment]
This isn't really meant as a general-purpose tool—it does precisely what I need to build the CodeMirror 6 libraries, and I'm not really interested in increasing its scope beyond that. Since it's pretty simple, I'd recommend forking it if you want to extend it.
